// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import SidebarLinkController from "./sidebar_link_controller"
application.register("sidebar-link", SidebarLinkController)

import VideoBackgroundController from "./video_background_controller"
application.register("video-background", VideoBackgroundController)
